// Generated by scripts/import-catalog.mjs. Client's existing product imagery.
export const catalogImages = {
  "catalog-mt-classic-tee-1-1": {
    "src": "/images/catalog/mt-classic-tee-1-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-2": {
    "src": "/images/catalog/mt-classic-tee-1-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-3": {
    "src": "/images/catalog/mt-classic-tee-1-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-4": {
    "src": "/images/catalog/mt-classic-tee-1-4.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-5": {
    "src": "/images/catalog/mt-classic-tee-1-5.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-6": {
    "src": "/images/catalog/mt-classic-tee-1-6.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-7": {
    "src": "/images/catalog/mt-classic-tee-1-7.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1-8": {
    "src": "/images/catalog/mt-classic-tee-1-8.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-pink-1": {
    "src": "/images/catalog/mt-classic-tee-pink-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-yellow-1": {
    "src": "/images/catalog/mt-classic-tee-yellow-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-purple-1": {
    "src": "/images/catalog/mt-classic-tee-purple-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-3-1": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-3-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-3-2": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-3-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-2-1": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-2-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-2-2": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-2-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-2-3": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-2-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-1-1": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-1-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-1-2": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-1-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-1-3": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-1-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-1": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-2": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-elite-3": {
    "src": "/images/catalog/mental-toughness-hoodie-elite-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-1": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-2": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-3": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-4": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-4.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-5": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-5.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-6": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-6.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-7": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-7.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-full-zip-hoodie-stay-strong-logo-8": {
    "src": "/images/catalog/mental-toughness-full-zip-hoodie-stay-strong-logo-8.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-black-full-zip-hoodie-og-logo-1": {
    "src": "/images/catalog/black-full-zip-hoodie-og-logo-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-black-full-zip-hoodie-og-logo-2": {
    "src": "/images/catalog/black-full-zip-hoodie-og-logo-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-black-full-zip-hoodie-og-logo-3": {
    "src": "/images/catalog/black-full-zip-hoodie-og-logo-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-black-full-zip-hoodie-og-logo-4": {
    "src": "/images/catalog/black-full-zip-hoodie-og-logo-4.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-outline-logo-1": {
    "src": "/images/catalog/mental-toughness-hoodie-outline-logo-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-outline-logo-2": {
    "src": "/images/catalog/mental-toughness-hoodie-outline-logo-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mental-toughness-hoodie-outline-logo-3": {
    "src": "/images/catalog/mental-toughness-hoodie-outline-logo-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-1": {
    "src": "/images/catalog/mt-classic-tee-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-2": {
    "src": "/images/catalog/mt-classic-tee-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-3": {
    "src": "/images/catalog/mt-classic-tee-3.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-4": {
    "src": "/images/catalog/mt-classic-tee-4.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-5": {
    "src": "/images/catalog/mt-classic-tee-5.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-classic-tee-6": {
    "src": "/images/catalog/mt-classic-tee-6.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-new-era-tee-1": {
    "src": "/images/catalog/mt-new-era-tee-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-new-era-tee-2": {
    "src": "/images/catalog/mt-new-era-tee-2.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-stay-strong-oversized-tee-1": {
    "src": "/images/catalog/mt-stay-strong-oversized-tee-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-tee-chest-logo-1": {
    "src": "/images/catalog/mt-tee-chest-logo-1.jpg",
    "width": 1200,
    "height": 1200
  },
  "catalog-mt-tee-chest-logo-2": {
    "src": "/images/catalog/mt-tee-chest-logo-2.jpg",
    "width": 1200,
    "height": 1200
  }
} as const;
