// GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Real pixel dimensions of every derivative in /public/images.
export const images = {
  "hoodie-red-front": {
    "src": "/images/products/hoodie-red-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-red-back": {
    "src": "/images/products/hoodie-red-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "hoodie-black-front": {
    "src": "/images/products/hoodie-black-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-black-back": {
    "src": "/images/products/hoodie-black-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "hoodie-white-front": {
    "src": "/images/products/hoodie-white-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-white-back": {
    "src": "/images/products/hoodie-white-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "tee-royal-front": {
    "src": "/images/products/tee-royal-front.jpg",
    "width": 1433,
    "height": 1600
  },
  "tee-royal-back": {
    "src": "/images/products/tee-royal-back.jpg",
    "width": 1433,
    "height": 1600
  },
  "joggers-black-front": {
    "src": "/images/products/joggers-black-front.jpg",
    "width": 1493,
    "height": 1600
  },
  "joggers-black-back": {
    "src": "/images/products/joggers-black-back.jpg",
    "width": 1493,
    "height": 1600
  },
  "shorts-black-front": {
    "src": "/images/products/shorts-black-front.jpg",
    "width": 1600,
    "height": 1451
  },
  "shorts-black-back": {
    "src": "/images/products/shorts-black-back.jpg",
    "width": 1600,
    "height": 1451
  },
  "rhinestone-hoodie-red": {
    "src": "/images/products/rhinestone-hoodie-red.png",
    "width": 485,
    "height": 512
  },
  "founder-millz": {
    "src": "/images/brand/founder-millz.jpg",
    "width": 710,
    "height": 943
  },
  "illus-core-tee-black": {
    "src": "/images/products/illus-core-tee-black.jpg",
    "width": 1433,
    "height": 1600
  },
  "illus-long-sleeve-tee-black": {
    "src": "/images/products/illus-long-sleeve-tee-black.jpg",
    "width": 1433,
    "height": 1600
  },
  "illus-long-sleeve-tee-red": {
    "src": "/images/products/illus-long-sleeve-tee-red.jpg",
    "width": 1433,
    "height": 1600
  },
  "illus-crewneck-sweatshirt-black": {
    "src": "/images/products/illus-crewneck-sweatshirt-black.jpg",
    "width": 1600,
    "height": 1281
  },
  "illus-crewneck-sweatshirt-red": {
    "src": "/images/products/illus-crewneck-sweatshirt-red.jpg",
    "width": 1600,
    "height": 1281
  },
  "illus-tank-top-black": {
    "src": "/images/products/illus-tank-top-black.jpg",
    "width": 1433,
    "height": 1600
  },
  "illus-tank-top-olive": {
    "src": "/images/products/illus-tank-top-olive.jpg",
    "width": 1433,
    "height": 1600
  },
  "illus-bucket-hat-black": {
    "src": "/images/products/illus-bucket-hat-black.jpg",
    "width": 1600,
    "height": 1600
  },
  "illus-bucket-hat-orange": {
    "src": "/images/products/illus-bucket-hat-orange.jpg",
    "width": 1600,
    "height": 1600
  },
  "illus-beanie-black": {
    "src": "/images/products/illus-beanie-black.jpg",
    "width": 1600,
    "height": 1600
  },
  "illus-beanie-red": {
    "src": "/images/products/illus-beanie-red.jpg",
    "width": 1600,
    "height": 1600
  }
} as const;

export type ImageKey = keyof typeof images;
