// GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Real pixel dimensions of every derivative in /public/images.
export const images = {
  "hoodie-red-front": {
    "src": "/images/products/hoodie-red-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-red-back": {
    "src": "/images/products/hoodie-red-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "hoodie-black-front": {
    "src": "/images/products/hoodie-black-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-black-back": {
    "src": "/images/products/hoodie-black-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "hoodie-white-front": {
    "src": "/images/products/hoodie-white-front.jpg",
    "width": 1600,
    "height": 1281
  },
  "hoodie-white-back": {
    "src": "/images/products/hoodie-white-back.jpg",
    "width": 1600,
    "height": 1240
  },
  "tee-royal-front": {
    "src": "/images/products/tee-royal-front.jpg",
    "width": 1433,
    "height": 1600
  },
  "tee-royal-back": {
    "src": "/images/products/tee-royal-back.jpg",
    "width": 1433,
    "height": 1600
  },
  "joggers-black-front": {
    "src": "/images/products/joggers-black-front.jpg",
    "width": 1493,
    "height": 1600
  },
  "joggers-black-back": {
    "src": "/images/products/joggers-black-back.jpg",
    "width": 1493,
    "height": 1600
  },
  "shorts-black-front": {
    "src": "/images/products/shorts-black-front.jpg",
    "width": 1600,
    "height": 1451
  },
  "shorts-black-back": {
    "src": "/images/products/shorts-black-back.jpg",
    "width": 1600,
    "height": 1451
  },
  "rhinestone-hoodie-red": {
    "src": "/images/products/rhinestone-hoodie-red.png",
    "width": 485,
    "height": 512
  },
  "founder-millz": {
    "src": "/images/brand/founder-millz.jpg",
    "width": 710,
    "height": 943
  }
} as const;

export type ImageKey = keyof typeof images;
