// One-time, reviewable snapshot of the client's public Shopify catalog.
// Run from the repository root. No credentials, checkout or live inventory sync.
import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import sharp from 'sharp';
const source = JSON.parse((await readFile('assets/catalog-source.json', 'utf8')).replace(/^\uFEFF/, ''));
const manifest = {};
await mkdir('public/images/catalog', { recursive: true });
for (const product of source.products) {
  for (const img of product.images) {
    const key = `catalog-${product.handle}-${img.position}`;
    const path = `/images/catalog/${product.handle}-${img.position}.jpg`;
    try { await access(`public${path}`); } catch {
      const response = await fetch(img.src);
      if (!response.ok) throw new Error(`Image fetch failed: ${response.status}`);
      await sharp(Buffer.from(await response.arrayBuffer())).rotate().resize({ width: 1200, height: 1200, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 85, mozjpeg: true }).toFile(`public${path}`);
    }
    const { width, height } = await sharp(`public${path}`).metadata();
    manifest[key] = { src: path, width, height };
  }
}
await writeFile('content/catalog-images.ts', `// Generated by scripts/import-catalog.mjs. Client's existing product imagery.\nexport const catalogImages = ${JSON.stringify(manifest, null, 2)} as const;\n`);
console.log(`Imported ${Object.keys(manifest).length} images from ${source.products.length} client products.`);

const swatches = { Black:'#202020', White:'#f7f7f5', Red:'#b92432', Maroon:'#682632', Navy:'#20273d', Pink:'#f5b9c6', Brown:'#45372f', 'Athletic Heather':'#969795', 'Heather True Royal':'#465797', 'Heather Prism Ice Blue':'#cce7e7', Mustard:'#e4a321', Natural:'#efe4cf', 'Sport Grey':'#b2b2b0', 'Light Heather Grey':'#cccac7', Royal:'#2162a9', Grey:'#8e918c' };
const slugify = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-');
const order = ['mt-classic-tee', 'mt-classic-tee-1', 'mt-new-era-tee', 'mt-stay-strong-oversized-tee', 'mt-tee-chest-logo', 'mt-classic-tee-pink', 'mt-classic-tee-purple', 'mt-classic-tee-yellow', 'mental-toughness-hoodie-elite', 'mental-toughness-hoodie-elite-1', 'mental-toughness-hoodie-elite-2', 'mental-toughness-hoodie-elite-3', 'mental-toughness-full-zip-hoodie-stay-strong-logo', 'black-full-zip-hoodie-og-logo', 'mental-toughness-hoodie-outline-logo'];
const decode = text => text.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').trim();
const catalog = source.products.map(p => {
  const colorOption = p.options.find(o => o.name === 'Color');
  const sizeOption = p.options.find(o => o.name === 'Size');
  const colors = [...colorOption.values].sort((a,b) => (a === 'Black' ? -1 : b === 'Black' ? 1 : 0));
  const colorways = colors.map(color => {
    const variants = p.variants.filter(v => v[`option${colorOption.position}`] === color);
    const front = p.images.find(i => i.id === variants[0].featured_image?.id);
    if (!front) throw new Error(`Unmapped color ${p.handle}/${color}`);
    const backPosition = p.handle === 'mt-new-era-tee' ? 2 : p.handle === 'black-full-zip-hoodie-og-logo' ? (color === 'Black' ? 3 : 4) : p.handle === 'mental-toughness-full-zip-hoodie-stay-strong-logo' ? (color === 'Black' ? 5 : 8) : null;
    const views = [{...front,view:'front'}, ...p.images.filter(i => i.position === backPosition).map(i => ({...i,view:'back'}))];
    return { slug:slugify(color), name:color, hex:swatches[color], images:views.map(i => ({key:`catalog-${p.handle}-${i.position}`, kind:'catalog', view:i.view, alt:`${p.title.trim().replace(/\s+/g,' ')} in ${color}, ${i.view} view from the Mental Toughness Clothing product catalog.`})), variants:variants.map(v => ({size:v[`option${sizeOption.position}`],price:Math.round(Number(v.price)*100),available:v.available,sourceId:String(v.id)})) };
  });
  const hoodie = p.product_type === 'Hoodie';
  const isClassic = p.handle.startsWith('mt-classic');
  const isZip = p.handle.includes('full-zip');
  const isRecycled = p.handle === 'black-full-zip-hoodie-og-logo';
  const isOversized = p.handle.includes('oversized');
  const graphicColor = p.title.match(/Elite\s+(\w+)/)?.[1];
  const name = p.handle === 'mt-classic-tee-1' ? 'MT Classic Tee — Light Colors' : graphicColor ? `Elite Hoodie — ${graphicColor}` : p.handle === 'mental-toughness-full-zip-hoodie-stay-strong-logo' ? 'Stay Strong Zip Hoodie' : isRecycled ? 'OG Logo Zip Hoodie' : p.handle === 'mental-toughness-hoodie-outline-logo' ? 'OG Outline Hoodie' : p.title.trim();
  const fabric = isRecycled ? '60% recycled cotton, 40% recycled polyester Re-Fleece.' : hoodie ? '50% cotton, 50% polyester. Medium-heavy fabric.' : isClassic ? 'Airlume combed and ring-spun cotton; fiber content varies in heather colors.' : isOversized ? '100% combed ring-spun cotton. Medium-weight fabric.' : '100% ring-spun US cotton. Garment-dyed, heavyweight fabric.';
  const summary = graphicColor ? `${graphicColor} Elite graphic on a cotton-blend pullover.` : isZip ? 'An easy everyday layer with a full metal zipper.' : hoodie ? 'A cotton-blend pullover with the outlined Mental Toughness monogram.' : isOversized ? 'A relaxed, oversized tee with the Stay Strong emblem.' : p.handle === 'mt-new-era-tee' ? 'Bold front monogram. Stay Strong artwork on the back.' : 'Everyday cotton with the Mental Toughness chest logo.';
  const fit = isOversized ? 'Relaxed, oversized fit.' : isRecycled ? 'Midweight layer with side seams for shape retention.' : hoodie ? 'Pullover with an adjustable hood and ribbed cuffs.' : 'Crew neck, short sleeves.';
  const table = p.body_html.match(/<table\b[\s\S]*?<\/table>/)?.[0];
  const tableRows = table ? [...table.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)].map(m => [...m[1].matchAll(/<t[hd]\b[^>]*>([\s\S]*?)<\/t[hd]>/g)].map(c=>decode(c[1]))) : [];
  const sizeChart = tableRows.length ? { sizes:tableRows[0].slice(1), rows:tableRows.slice(1).filter(r=>r[0].endsWith(', in')).map(r=>({label:r[0],values:r.slice(1)})) } : undefined;
  const prices = p.variants.map(v=>Math.round(Number(v.price)*100));
  return {slug:p.handle, name, category:hoodie?'fleece':'tees', line:'print', price:Math.min(...prices), priceVaries:new Set(prices).size>1, sizeUpcharge:null, sizes:sizeOption.values, sizeGuide:hoodie?'hoodie':'tee', summary, description:`${summary} ${fabric}`, details:{fabric,fit:isZip?'Full zip with an adjustable hood.':fit,print:graphicColor?`${graphicColor} Elite chest graphic.`:p.handle==='mt-new-era-tee'?'Monogram on the front; Stay Strong artwork on the back.':isOversized||p.handle.includes('stay-strong-logo')?'Stay Strong logo.':'Mental Toughness logo.'}, care:['Machine wash cold with similar colors.','Tumble dry low.','Do not iron directly on the artwork.'], colorways, order:order.indexOf(p.handle)-20, confirmed:false, source:{url:`https://mentaltoughnessclothing.shop/products/${p.handle}`,checkedAt:'2026-09-09'}, ...(sizeChart?{sizeChart}:{})};
});
await writeFile('content/catalog-products.ts', `// Generated from the client storefront snapshot. No live inventory synchronization.\nimport type { Product } from './products';\nexport const catalogProducts = ${JSON.stringify(catalog,null,2)} as const satisfies readonly Product[];\n`);
