// Traces assets/logo.jpg (359×500, black on white JPEG) into a crisp SVG.
// The mark is straight-edged, so the trace is run with alphaMax = 0 (no curve
// smoothing): every corner stays a corner and the output is a small polygon.
// Result: public/images/brand/monogram.svg — removes the ~138px ceiling the
// JPEG imposed (see ASSET-INVENTORY.md). A designer-supplied vector should
// still replace this; see CLIENT-TODO.md.
import potrace from "potrace";
import sharp from "sharp";
import { writeFile, mkdir } from "node:fs/promises";

const SRC = "assets/logo.jpg";
const OUT_DIR = "public/images/brand";
await mkdir(OUT_DIR, { recursive: true });

// Upscale 4× with a hard threshold first so potrace sees clean edges.
const up = await sharp(SRC)
  .resize({ width: 359 * 4, kernel: "lanczos3" })
  .grayscale()
  .threshold(128)
  .png()
  .toBuffer();

const svgRaw = await new Promise((resolve, reject) => {
  potrace.trace(
    up,
    {
      threshold: 128,
      turdSize: 40,
      alphaMax: 0, // keep corners sharp — the mark has no curves
      optCurve: false,
      turnPolicy: potrace.Potrace.TURNPOLICY_MINORITY,
      color: "currentColor",
      background: "transparent",
    },
    (err, svg) => (err ? reject(err) : resolve(svg)),
  );
});

// Pull the path data and the traced size.
const d = svgRaw.match(/ d="([^"]+)"/)[1];
const w = Number(svgRaw.match(/width="(\d+)/)[1]);
const h = Number(svgRaw.match(/height="(\d+)/)[1]);

// Compute a tight bounding box from the absolute coordinates in the path.
const nums = d.match(/-?\d+(\.\d+)?/g).map(Number);
let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
for (let i = 0; i + 1 < nums.length; i += 2) {
  const x = nums[i], y = nums[i + 1];
  if (x < minX) minX = x; if (x > maxX) maxX = x;
  if (y < minY) minY = y; if (y > maxY) maxY = y;
}
const pad = 4;
const vb = `${(minX - pad).toFixed(1)} ${(minY - pad).toFixed(1)} ${(maxX - minX + 2 * pad).toFixed(1)} ${(maxY - minY + 2 * pad).toFixed(1)}`;

// Round coordinates to one decimal to keep the file small.
const dRounded = d.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" fill="currentColor" role="img" aria-label="Mental Toughness TM monogram"><path d="${dRounded}"/></svg>\n`;
await writeFile(`${OUT_DIR}/monogram.svg`, svg);

// Preview render for eyeballing, plus icon PNGs.
const render = (size, bg) =>
  sharp(Buffer.from(svg.replace("currentColor", "#EDE7DC").replace('fill="#EDE7DC"', 'fill="#EDE7DC"')), { density: 400 })
    .resize(size, size, { fit: "contain", background: bg })
    .flatten({ background: bg })
    .png();

await render(800, "#0E0D12").toFile("/private/tmp/claude-503/-Users-nahi-Documents-Github-mental-toughness-clothing/afcd4176-a833-4a10-9094-2ad6a60ad9af/scratchpad/preview/monogram-trace.png");

console.log(`traced ${w}×${h} → viewBox ${vb}; path ${dRounded.length} chars, ${nums.length / 2} points`);

// Also emit the path as a TS constant so the mark can be inlined with currentColor.
await writeFile(
  "components/brand/monogram-path.ts",
  `// GENERATED by scripts/trace-logo.mjs from assets/logo.jpg — do not edit by hand.
// Traced with corner-preserving settings; see DECISIONS.md §6.
export const MONOGRAM_VIEWBOX = "${vb}";
export const MONOGRAM_PATH =
  "${dRounded}";
`,
);
